coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.01
    patch: false
    changes: false
comment:
  layout: "header, diff, sunburst, uncovered"
  behavior: default
codecov:
  token: 057953e4-d263-41c0-913c-5d45c0371df9